'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MessageBoxTemplate

    '''<summary>
    '''MsgBoxPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBoxPopUp As Global.AjaxControlToolkit.ModalPopupExtender

    '''<summary>
    '''pnlPopUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopUp As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''pnlPopUpBarra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlPopUpBarra As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''MsgBoxTitulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBoxTitulo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CancelMessageButtonCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CancelMessageButtonCliente As Global.System.Web.UI.HtmlControls.HtmlInputImage

    '''<summary>
    '''MsgBoxMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBoxMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''MsgBoxIcono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MsgBoxIcono As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''OkMessageButtonCliente33 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OkMessageButtonCliente33 As Global.System.Web.UI.WebControls.Button
End Class
