//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebPunteoElectronico.Site.ConsultaFirmas {
    
    
    public partial class Consulta_Firmas_Data {
    }
}
