 

/*
Autogenerated
Soluciones Logicas Yayan Gaia
Mapa de navigacion del sitio Web
*/

namespace Miharu.Client.Browser
{
	public static class Navigation
	{
		public static class controls
		{
			public const string proxy_data = "~/controls/proxy_data.aspx";
		}
		public static class site
		{
			public const string main = "~/site/main.aspx";
			public static class account
			{
				public const string change_password = "~/site/account/change_password.aspx";
				public const string connect = "~/site/account/connect.aspx";
				public const string forgotten_password = "~/site/account/forgotten_password.aspx";
				public const string login = "~/site/account/login.aspx";
				public const string restore_password = "~/site/account/restore_password.aspx";
			}
			public static class administracion
			{
				public static class seguridad
				{
					public const string desbloqueo_ip = "~/site/administracion/seguridad/desbloqueo_ip.aspx";
					public const string esquemas = "~/site/administracion/seguridad/esquemas.aspx";
					public const string roles = "~/site/administracion/seguridad/roles.aspx";
					public const string usuarios = "~/site/administracion/seguridad/usuarios.aspx";
				}
			}
			public static class application
			{
				public const string about = "~/site/application/about.aspx";
				public const string dashboard = "~/site/application/dashboard.aspx";
			}
			public static class consulta
			{
				public const string consultas = "~/site/consulta/consultas.aspx";
			}
			public static class informes
			{
				public const string web_report_viewer = "~/site/informes/web_report_viewer.aspx";
			}
			public static class reportes
			{
				public const string reporte_resumen_movimiento = "~/site/reportes/reporte_resumen_movimiento.aspx";
			}
		}
	}
}


