//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Miharu.Data.Bridge.DataRemoteService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DataRemoteServiceSoap", Namespace="http://tempuri.org/")]
    public partial class DataRemoteService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback dataBridgeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImageCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFolioCargueItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFoliosFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFolioFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateImageFolioManagerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFolioOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendDataPostRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFoliosCargueItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DataRemoteService() {
            this.Url = global::Miharu.Data.Bridge.Properties.Settings.Default.Miharu_Data_Bridge_DataRemoteService_DataRemoteService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event dataBridgeCompletedEventHandler dataBridgeCompleted;
        
        /// <remarks/>
        public event ImageCountCompletedEventHandler ImageCountCompleted;
        
        /// <remarks/>
        public event GetFolioCargueItemCompletedEventHandler GetFolioCargueItemCompleted;
        
        /// <remarks/>
        public event GetFoliosFileCompletedEventHandler GetFoliosFileCompleted;
        
        /// <remarks/>
        public event GetFolioFileCompletedEventHandler GetFolioFileCompleted;
        
        /// <remarks/>
        public event CreateImageFolioManagerCompletedEventHandler CreateImageFolioManagerCompleted;
        
        /// <remarks/>
        public event GetFolioCompletedEventHandler GetFolioCompleted;
        
        /// <remarks/>
        public event SendDataPostRequestCompletedEventHandler SendDataPostRequestCompleted;
        
        /// <remarks/>
        public event GetFoliosCargueItemCompletedEventHandler GetFoliosCargueItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dataBridge", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dataBridge(string request) {
            object[] results = this.Invoke("dataBridge", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dataBridgeAsync(string request) {
            this.dataBridgeAsync(request, null);
        }
        
        /// <remarks/>
        public void dataBridgeAsync(string request, object userState) {
            if ((this.dataBridgeOperationCompleted == null)) {
                this.dataBridgeOperationCompleted = new System.Threading.SendOrPostCallback(this.OndataBridgeOperationCompleted);
            }
            this.InvokeAsync("dataBridge", new object[] {
                        request}, this.dataBridgeOperationCompleted, userState);
        }
        
        private void OndataBridgeOperationCompleted(object arg) {
            if ((this.dataBridgeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dataBridgeCompleted(this, new dataBridgeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImageCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ImageCount(string request) {
            object[] results = this.Invoke("ImageCount", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ImageCountAsync(string request) {
            this.ImageCountAsync(request, null);
        }
        
        /// <remarks/>
        public void ImageCountAsync(string request, object userState) {
            if ((this.ImageCountOperationCompleted == null)) {
                this.ImageCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImageCountOperationCompleted);
            }
            this.InvokeAsync("ImageCount", new object[] {
                        request}, this.ImageCountOperationCompleted, userState);
        }
        
        private void OnImageCountOperationCompleted(object arg) {
            if ((this.ImageCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImageCountCompleted(this, new ImageCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFolioCargueItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFolioCargueItem(string request) {
            object[] results = this.Invoke("GetFolioCargueItem", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFolioCargueItemAsync(string request) {
            this.GetFolioCargueItemAsync(request, null);
        }
        
        /// <remarks/>
        public void GetFolioCargueItemAsync(string request, object userState) {
            if ((this.GetFolioCargueItemOperationCompleted == null)) {
                this.GetFolioCargueItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFolioCargueItemOperationCompleted);
            }
            this.InvokeAsync("GetFolioCargueItem", new object[] {
                        request}, this.GetFolioCargueItemOperationCompleted, userState);
        }
        
        private void OnGetFolioCargueItemOperationCompleted(object arg) {
            if ((this.GetFolioCargueItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFolioCargueItemCompleted(this, new GetFolioCargueItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFoliosFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFoliosFile(string request) {
            object[] results = this.Invoke("GetFoliosFile", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFoliosFileAsync(string request) {
            this.GetFoliosFileAsync(request, null);
        }
        
        /// <remarks/>
        public void GetFoliosFileAsync(string request, object userState) {
            if ((this.GetFoliosFileOperationCompleted == null)) {
                this.GetFoliosFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFoliosFileOperationCompleted);
            }
            this.InvokeAsync("GetFoliosFile", new object[] {
                        request}, this.GetFoliosFileOperationCompleted, userState);
        }
        
        private void OnGetFoliosFileOperationCompleted(object arg) {
            if ((this.GetFoliosFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFoliosFileCompleted(this, new GetFoliosFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFolioFile", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFolioFile(string request) {
            object[] results = this.Invoke("GetFolioFile", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFolioFileAsync(string request) {
            this.GetFolioFileAsync(request, null);
        }
        
        /// <remarks/>
        public void GetFolioFileAsync(string request, object userState) {
            if ((this.GetFolioFileOperationCompleted == null)) {
                this.GetFolioFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFolioFileOperationCompleted);
            }
            this.InvokeAsync("GetFolioFile", new object[] {
                        request}, this.GetFolioFileOperationCompleted, userState);
        }
        
        private void OnGetFolioFileOperationCompleted(object arg) {
            if ((this.GetFolioFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFolioFileCompleted(this, new GetFolioFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateImageFolioManager", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateImageFolioManager(string request) {
            object[] results = this.Invoke("CreateImageFolioManager", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateImageFolioManagerAsync(string request) {
            this.CreateImageFolioManagerAsync(request, null);
        }
        
        /// <remarks/>
        public void CreateImageFolioManagerAsync(string request, object userState) {
            if ((this.CreateImageFolioManagerOperationCompleted == null)) {
                this.CreateImageFolioManagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateImageFolioManagerOperationCompleted);
            }
            this.InvokeAsync("CreateImageFolioManager", new object[] {
                        request}, this.CreateImageFolioManagerOperationCompleted, userState);
        }
        
        private void OnCreateImageFolioManagerOperationCompleted(object arg) {
            if ((this.CreateImageFolioManagerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateImageFolioManagerCompleted(this, new CreateImageFolioManagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFolio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFolio(string request) {
            object[] results = this.Invoke("GetFolio", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFolioAsync(string request) {
            this.GetFolioAsync(request, null);
        }
        
        /// <remarks/>
        public void GetFolioAsync(string request, object userState) {
            if ((this.GetFolioOperationCompleted == null)) {
                this.GetFolioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFolioOperationCompleted);
            }
            this.InvokeAsync("GetFolio", new object[] {
                        request}, this.GetFolioOperationCompleted, userState);
        }
        
        private void OnGetFolioOperationCompleted(object arg) {
            if ((this.GetFolioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFolioCompleted(this, new GetFolioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendDataPostRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendDataPostRequest(string request) {
            object[] results = this.Invoke("SendDataPostRequest", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendDataPostRequestAsync(string request) {
            this.SendDataPostRequestAsync(request, null);
        }
        
        /// <remarks/>
        public void SendDataPostRequestAsync(string request, object userState) {
            if ((this.SendDataPostRequestOperationCompleted == null)) {
                this.SendDataPostRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendDataPostRequestOperationCompleted);
            }
            this.InvokeAsync("SendDataPostRequest", new object[] {
                        request}, this.SendDataPostRequestOperationCompleted, userState);
        }
        
        private void OnSendDataPostRequestOperationCompleted(object arg) {
            if ((this.SendDataPostRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendDataPostRequestCompleted(this, new SendDataPostRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFoliosCargueItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFoliosCargueItem(string request) {
            object[] results = this.Invoke("GetFoliosCargueItem", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFoliosCargueItemAsync(string request) {
            this.GetFoliosCargueItemAsync(request, null);
        }
        
        /// <remarks/>
        public void GetFoliosCargueItemAsync(string request, object userState) {
            if ((this.GetFoliosCargueItemOperationCompleted == null)) {
                this.GetFoliosCargueItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFoliosCargueItemOperationCompleted);
            }
            this.InvokeAsync("GetFoliosCargueItem", new object[] {
                        request}, this.GetFoliosCargueItemOperationCompleted, userState);
        }
        
        private void OnGetFoliosCargueItemOperationCompleted(object arg) {
            if ((this.GetFoliosCargueItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFoliosCargueItemCompleted(this, new GetFoliosCargueItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void dataBridgeCompletedEventHandler(object sender, dataBridgeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dataBridgeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dataBridgeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ImageCountCompletedEventHandler(object sender, ImageCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImageCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImageCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFolioCargueItemCompletedEventHandler(object sender, GetFolioCargueItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFolioCargueItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFolioCargueItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFoliosFileCompletedEventHandler(object sender, GetFoliosFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFoliosFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFoliosFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFolioFileCompletedEventHandler(object sender, GetFolioFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFolioFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFolioFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void CreateImageFolioManagerCompletedEventHandler(object sender, CreateImageFolioManagerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateImageFolioManagerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateImageFolioManagerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFolioCompletedEventHandler(object sender, GetFolioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFolioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFolioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void SendDataPostRequestCompletedEventHandler(object sender, SendDataPostRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendDataPostRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendDataPostRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void GetFoliosCargueItemCompletedEventHandler(object sender, GetFoliosCargueItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFoliosCargueItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFoliosCargueItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591